site_name: 勉強会 資料集
copyright: 'Copyright © 2022 kota'

theme:
  name: material
  language: ja
  custom_dir: overrides
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    # - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.expand
    # - navigation.top
    - toc.integrate

nav:
  - ウェブサイト制作:
    - ウェブサイト制作 - シラバス: web/syllabus.md
    - ウェブサイト制作 - 01: web/01.md
    - ウェブサイト制作 - 02: web/02.md
    - ウェブサイト制作 - 03: web/03.md
    - ウェブサイト制作 - 04: web/04.md
    - ウェブサイト制作 - 05: web/05.md
    - ウェブサイト制作 - 06: web/06.md

  - Git:
    - Git - インストール: git/install.md
    - Git - 使い方: git/usage.md

  - Github:
    - Github - アカウント登録: github/setup.md
    - Github - 使い方: github/usage.md

  - VSCode:
    - VSCode - インストール: vscode/install.md
    - VSCode - 使い方: vscode/usage.md
    - VSCode - ショートカットキー: vscode/shortcut.md
    - VSCode - 拡張機能: vscode/extensions.md
    - VSCode - c1-byodを追加する: vscode/c1byod.md

extra:
  search:
    language: 'ja'
  analytics:
    provider: google
    property: G-BGCQ05X1GQ
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yashikota/meetup

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - toc:
      permalink: true