site_name: 勉強会 資料集
copyright: 'Copyright © 2022 kota'

theme:
  name: material
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    # - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.expand
    # - navigation.top
    - toc.integrate

nav:
  - ウェブサイト制作:
    - シラバス: web/syllabus.md
    - 第1回: web/01.md
    - 第2回: web/02.md
    - 第3回: web/03.md
    - 第4回: web/04.md
    - 第5回: web/05.md
    - 第6回: web/06.md

  - Git:
    - インストール: git/install.md
    - 初期設定: git/setup.md

  - Github:
    - インストール: github/install.md
    - 初期設定: github/setup.md

  - VSCode:
    - インストール: vscode/install.md
    - 初期設定: vscode/setup.md

extra:
  search:
      language: 'ja'
  analytics:
      provider: google
      property: G-BGCQ05X1GQ

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - toc:
      permalink: true